name: Report a bug
description: Tell me about a bug or issue you may have identified in Resumy.
title: "Provide a general summary of the issue"
labels: [bug]
assignees: [alexlren]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: Provide a summary of the issue and what you expected to happen, including specific steps to reproduce. You can also attach a screenshot if relevant by dragging and dropping it here.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system(s) are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Android
        - iOS
        - Linux
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What version are you using?
      placeholder: "e.g., v0.0.1"
    validations:
      required: false
